name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build-apk:
    name: Build APK using Buildozer
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          zip \
          unzip \
          git \
          openjdk-17-jdk \
          python3-pip \
          build-essential \
          libssl-dev \
          libffi-dev \
          libz-dev \
          libjpeg-dev \
          libblas-dev \
          liblapack-dev \
          pkg-config \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0 \
          libmtdev-dev \
          libgl1-mesa-dev \
          libgles2-mesa-dev \
          libbz2-dev \
          libsqlite3-dev \
          libgstreamer-plugins-base1.0-dev \
          libpulse-dev \
          libx11-dev \
          libxcursor-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxi-dev \
          libasound2-dev \
          libudev-dev \
          libfreetype6-dev \
          libncursesw5-dev

    - name: Install Android SDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        unzip sdk.zip -d latest
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-31" "build-tools;33.0.2"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython virtualenv buildozer

    - name: Build APK
      run: |
        buildozer init || true
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-apk
        path: bin/*.apk
