name: Build Elara APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            zip \
            openjdk-17-jdk \
            python3-pip \
            python3-setuptools \
            libncurses5 \
            libstdc++6 \
            zlib1g-dev \
            libffi-dev \
            libssl-dev \
            libjpeg-dev \
            libsqlite3-dev \
            libbz2-dev \
            libreadline-dev \
            liblzma-dev \
            autoconf \
            libtool \
            pkg-config \
            unzip \
            ccache \
            libpython3-dev \
            curl

      - name: Install Python deps
        run: |
          python3 -m pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Elara-APK
          path: bin/*.apk
