- name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            libstdc++6 \
            libc6 \
            zlib1g-dev \
            libssl-dev \
            libffi-dev \
            libncurses6 \
            curl
