name: Build Elara APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools zip unzip openjdk-17-jdk
        pip3 install --user buildozer cython

    - name: Build the APK
      run: |
        export PATH=$HOME/.local/bin:$PATH
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: elara-debug-apk
        path: bin/*.apk
