name: Build Elara APK

on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read

jobs:
  build:
    name: Build APK using Buildozer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            python3-setuptools \
            libz-dev \
            libjpeg-dev \
            libfreetype6-dev \
            libpng-dev \
            libffi-dev \
            liblzma-dev \
            libncurses5-dev \
            libreadline-dev \
            libsqlite3-dev \
            libssl-dev \
            autoconf \
            libtool \
            pkg-config \
            curl \
            libyaml-dev \
            libxml2-dev \
            libxslt-dev \
            zlib1g-dev

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@main
        with:
          name: Elara-APK
          path: bin/*.apk
