name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            zip unzip git curl libncurses5 \
            libffi-dev libssl-dev libbz2-dev \
            libsqlite3-dev libreadline-dev \
            liblzma-dev

      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip sdk.zip -d latest
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;33.0.2"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install cython virtualenv buildozer

      - name: Build APK
        run: |
          cd <TU_TWOJE_FOLDER_Z_PLIKAMI>
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: my-apk
