name: Build Elara APK

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential ccache \
            libffi-dev libssl-dev \
            libsqlite3-dev zlib1g-dev \
            libncurses5-dev libncursesw5-dev \
            libreadline-dev libgdbm-dev libbz2-dev \
            liblzma-dev libgmp-dev libexpat1-dev \
            libx11-dev libxext-dev libxrender-dev \
            libstdc++6 gcc g++ unzip wget curl \
            openjdk-17-jdk

      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O sdk.zip
          unzip sdk.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;33.0.2" "platforms;android-31"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install cython buildozer

      - name: Build APK using Buildozer
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@master
        with:
          name: Elara-APK
          path: bin/*.apk
