name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            ccache \
            libffi-dev \
            libssl-dev \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            zlib1g-dev \
            libncurses5 \
            libstdc++6 \
            libsqlite3-dev \
            git \
            unzip \
            openjdk-17-jdk \
            curl

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install cython==0.29.33 virtualenv buildozer

      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ElaraLite-APK
          path: bin/*.apk
