name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build_apk:
    name: Build APK using Buildozer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            ccache \
            git \
            libncurses5 \
            libffi-dev \
            libssl-dev \
            liblzma-dev \
            libjpeg-dev \
            zlib1g-dev \
            libavdevice-dev \
            libavfilter-dev \
            libopus-dev \
            libsdl2-dev \
            unzip \
            zip \
            openjdk-17-jdk \
