name: Build ElaraLite APK

on:
  push:
    branches:
      - main # Zmień na nazwę Twojej głównej gałęzi, jeśli jest inna

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/kivy/buildozer:1.6.0 # Zmieniono tag z stable na konkretną wersję

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python dependencies for Buildozer
        run: |
          set -e
          python3 -m pip install --upgrade pip
          pip install cython==0.29.36 virtualenv buildozer

      - name: Build APK with Buildozer
        run: |
          set -e
          yes | buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ElaraLite-APK
          path: bin/*.apk
