name: Build Elara APK

on: push: branches: - main

permissions: contents: read

jobs: build: name: Build APK using Buildozer runs-on: ubuntu-latest

steps:
  - name: Checkout repo
    uses: actions/checkout@v3

  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'

  - name: Install system dependencies
    run: |
      sudo apt update
      sudo apt install -y \
        build-essential \
        git \
        zip \
        unzip \
        openjdk-17-jdk \
        zlib1g-dev \
        libffi-dev \
        libssl-dev \
        libjpeg-dev \
        libSDL2-dev \
        libmtdev-dev \
        libgl1-mesa-dev \
        libgles2-mesa-dev \
        libgstreamer1.0 \
        libgstreamer1.0-dev \
        libavcodec-dev \
        libavformat-dev \
        libswscale-dev \
        libfreetype6-dev \
        libpng-dev \
        libsqlite3-dev \
        libusb-dev \
        autoconf \
        libtool \
        pkg-config \
        libyaml-dev \
        curl

  - name: Install Python dependencies
    run: |
      python -m pip install --upgrade pip
      pip install cython buildozer

  - name: Build APK
    run: buildozer android debug

  - name: Upload APK
    uses: actions/upload-artifact@v4
    with:
      name: Elara-APK
      path: bin/*.apk

